### ISSUE TITLE
Error gramatical en página 68

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-descubre-svelte-issues#10]
La siguiente frase no es correcta:

'Supongo que te habrás dado cuenta que en el test anterior estamos haciendo una llamada a la API de
The Movie Database.'

dar(se) cuenta. Esta locución verbal va siempre seguida de un complemento precedido de la preposición _de_. [(RAE)](https://www.rae.es/dpd/dar)

Forma correcta: 
''Supongo que te habrás dado cuenta **de** que en el test anterior estamos haciendo una llamada a la API de
The Movie Database.''

**Comment by midudev** [comment]
👍
