### ISSUE TITLE
Falta traducción en página 20

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-descubre-svelte-issues#2]
En el segundo párrafo después del Playground falta una traducción:

'Como counter se inicia a 0, al principio el mensaje es Es par pero... si hacemos click en el botón,
el counter se incrementa en 3 pero, sin embargo, el mensaje que vemos todavía es ➡️Is Even⬅️, lo que
significa que no está mostrando el mensaje correcto. ¿Por qué?'

Cuando se hace referencia al valor de la variable `message`, el valor siempre es 'Es par' menos en este caso en el que está en inglés.

**Comment by midudev** [comment]
Arreglado para la próxima. :)
