### ISSUE TITLE
Error gramatical página 57

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-descubre-svelte-issues#8]
La siguiente frase no es correcta:

'¿Quieres asegurarte que todo funciona correctamente?'

El verbo _asegurar_ se construye con la preposición _de_ cuando se emplea de forma pronominal con el sentido de ‘confirmar o aseverar la realidad o certeza de algo’. Solución:

'¿Quieres asegurarte de que todo funciona correctamente?'

**Comment by cipriansauliuc** [comment]
Mismo error en página 61:

'Ya sabemos desplegar nuestra aplicación pero todavía no hemos visto cómo podemos automatizar
un proceso para asegurarnos que lo que llevamos a producción es correcto.'

Incorrecto: 'asegurarnos que'
Correcto: 'asegurarnos de que'

**Comment by cipriansauliuc** [comment]
Mismo error en página 66:

'Ejercicio: Con todo lo que has aprendido hasta este punto, deberías poder asegurarte que nuestro
componente también renderiza el título y el año.'

Incorrecto: 'asegurarte que'
Correcto: 'asegurarte de que'

**Comment by midudev** [comment]
👏
